b13/b13/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("accounts/", include("allauth.urls")),
    path("", include("hoos.urls"))
]

b13/hoos/urls.py
from django.urls import path
from . import views
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path("", views.home, name='home'),
    path("logout/", views.logout_view, name='logout'),
    path("hoos_login/", views.admin_login, name='authenticate'),

    path('welcome/', views.welcome, name='welcome'),
    path('listings/', views.listings, name='listings'),
    path('map/', views.map_view, name='map'),
    path('submit_event/', views.submit_event, name='submit_event'),
    path('review_events/', views.review_events, name='review_events'),
    path('approve_event/<int:event_id>/', views.approve_event, name='approve_event'),
    path('reject_event/<int:event_id>/', views.reject_event, name='reject_event'),
    path('delete_event/<int:event_id>/', views.delete_event, name='delete_event'),
    path('my_events/', views.my_events, name='my_events'),
    path('event_details/<int:event_id>/', views.event_details, name='event_details'),
]

b13/hoos/models.py
from django.conf import settings
from django.db import models
from django.utils.translation import gettext_lazy as _


class Tag(models.Model):
    name = models.CharField(max_length=50, unique=True)

    def __str__(self):
        return self.name

class EventSubmission(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    name = models.CharField(max_length=200)
    description = models.TextField()
    location = models.CharField(max_length=200)
    latitude = models.FloatField(null=True, blank=True)
    longitude = models.FloatField(null=True, blank=True)
    date_time = models.DateTimeField(default=None)
    tags = models.ManyToManyField(Tag, null=True, blank=True)
    date_time_created = models.DateTimeField(auto_now_add=True)

    APPROVAL_CHOICES = [
        ('pending', '⏰ Pending'),
        ('approved', '✅ Approved'),
        ('rejected', '❌ Rejected'),
    ]

    approval_status = models.CharField(
        max_length=20,
        choices=APPROVAL_CHOICES,
        default='pending',
    )

    def __str__(self):
        return f"{self.name} by {self.user.username}"

b13/hoos/forms.py
from django import forms
from .models import EventSubmission, Tag
from django.core.exceptions import ValidationError
from django.utils import timezone

class DateTimeInput(forms.DateTimeInput):
    input_type = 'datetime'

class EventSubmissionForm(forms.ModelForm):
    class Meta:
        model = EventSubmission
        fields = ['name', 'description', 'location', 'date_time', 'tags']
        widgets = {
            'location': forms.TextInput(attrs={'id': 'autocomplete'}),
            'date_time': forms.DateTimeInput(attrs={'type': 'datetime-local'})
        }

    tags = forms.ModelMultipleChoiceField(
        queryset=Tag.objects.all(),
        widget=forms.CheckboxSelectMultiple,
        required=False,
    )

    def clean_date_time(self):
        date_time = self.cleaned_data.get('date_time')

        if date_time and date_time < timezone.now():
            raise ValidationError("Event cannot be in the past.")

        return date_time

b13/hoos/views.py
import googlemaps
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import logout
from .forms import EventSubmissionForm
from .models import EventSubmission
from .models import Tag
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.core.exceptions import ValidationError
from django.utils import timezone

def check_authenticated(request):
    pass

def is_admin(user):
    return user.is_authenticated and user.is_superuser

def assign_approval_status(request, event_id, approval_status):
    event = get_object_or_404(EventSubmission, id=event_id)
    redirect_url = request.META.get('HTTP_REFERER', reverse('home'))
    event.approval_status = approval_status
    event.save()
    return redirect(redirect_url)

# Create your views here.
def home(request):
    if request.user.is_authenticated:
        return redirect('welcome')
    return render(request, "home.html")

def logout_view(request):
    logout(request)
    return redirect("/")

def welcome(request):
    if not request.user.is_authenticated:
        return redirect('home')
    user_type = 'an Admin' if is_admin(request.user) else 'a User'
    return render(request, 'welcome.html', context={'user_type': user_type})

def admin_login(request):
    if request.user.is_authenticated and request.user.is_superuser:
            return redirect('home_admin')
    return redirect('home_user')

def submit_event(request):
    if not request.user.is_authenticated:
        return redirect('home')
    if request.method == 'POST':
        form = EventSubmissionForm(request.POST)
        # try:
        if form.is_valid():
            submission = form.save(commit=False)
            gmaps = googlemaps.Client(key='AIzaSyBFnP0Yo4IN8h8Q1U4SjPKdJH9X1QeiKMc')
            geocode_result = gmaps.geocode(submission.location)
            if geocode_result:
                submission.latitude = geocode_result[0]['geometry']['location']['lat']
                submission.longitude = geocode_result[0]['geometry']['location']['lng']
            submission.user = request.user
            form.save()
            context = {'submission': submission, 'valid_location': bool(geocode_result)}
            return render(request, 'submit_confirmation.html', context=context)
        else:
            if 'date_time' not in form.errors:
                form.add_error('date_time', 'Event cannot be in the past.')
        # except ValidationError as e:
        #     form.add_error('date_time', e)
    else:
        form = EventSubmissionForm()
    return render(request, 'submit.html', {'form': form})

def review_events(request):
    if not request.user.is_authenticated:
        return redirect('home')
    if not is_admin(request.user):
        return redirect('home')
    events = EventSubmission.objects.filter(approval_status='pending')
    return render(request, 'review.html', {'events': events})

def approve_event(request, event_id):
    if not request.user.is_authenticated:
        return redirect('home')
    if not is_admin(request.user):
        return redirect('home')
    return assign_approval_status(request, event_id, 'approved')

def reject_event(request, event_id):
    if not request.user.is_authenticated:
        return redirect('home')
    if not is_admin(request.user):
        return redirect('home')
    return assign_approval_status(request, event_id, 'rejected')

def delete_event(request, event_id):
    if not request.user.is_authenticated:
        return redirect('home')
    
    event = get_object_or_404(EventSubmission, id=event_id)
    redirect_url = request.META.get('HTTP_REFERER', reverse('home'))
    event.delete()
    return redirect(redirect_url)

def listings(request):
    if not request.user.is_authenticated:
        return redirect('home')
    events = EventSubmission.objects.filter(
        approval_status='approved',
        date_time__gte=timezone.now(),
    ).order_by('date_time')
    show_btn = False
    name = ""
    form = EventSubmissionForm()
    tag_filter = request.GET.getlist('tags')
    if tag_filter:
        for tag in tag_filter:
            events = events.filter(tags=tag).order_by('date_time')
        form = EventSubmissionForm(initial={'tags': tag_filter})
        show_btn = True
    name_filter = request.GET.get('name')
    if name_filter:
        events = events.filter(name__icontains=name_filter).order_by('date_time')
        show_btn = True
        name = name_filter
    date_filter = [request.GET.get("after"), request.GET.get("before")]
    if date_filter[0]:
        events = events.filter(date_time__gt=date_filter[0]).order_by('date_time')
        show_btn = True
    if date_filter[1]:
        events = events.filter(date_time__lt=date_filter[1]).order_by('date_time')
        show_btn = True
    return render(request, 'listings.html', context={'events': events, 'form': form, 'show': show_btn, 'name': name, 'tags': tag_filter, 'date': date_filter})

def map_view(request):
    if not request.user.is_authenticated:
        return redirect('home')
    events = EventSubmission.objects.filter(approval_status='approved', date_time__gte=timezone.now())
    show_btn = False
    name = ""
    form = EventSubmissionForm()
    tag_filter = request.GET.getlist('tags')
    if tag_filter:
        for tag in tag_filter:
            events = events.filter(tags=tag)
        form = EventSubmissionForm(initial={'tags': tag_filter})
        show_btn = True
    name_filter = request.GET.get('name')
    if name_filter:
        events = events.filter(name__icontains=name_filter)
        show_btn = True
        name = name_filter
    date_filter = [request.GET.get("after"), request.GET.get("before")]
    if date_filter[0]:
        events = events.filter(date_time__gt=date_filter[0])
        show_btn = True
    if date_filter[1]:
        events = events.filter(date_time__lt=date_filter[1])
        show_btn = True
    return render(request, "map.html", context={'events': events, 'form': form, 'show': show_btn, 'name': name, 'tags': tag_filter, 'date': date_filter})

def my_events(request):
    if not request.user.is_authenticated:
        return redirect('home')
    events = EventSubmission.objects.filter(user=request.user)
    return render(request, 'my_events.html', context={'events': events})

def event_details(request, event_id):
    if not request.user.is_authenticated:
        return redirect('home')
    event = get_object_or_404(EventSubmission, id=event_id)
    context = {'event': event, 'long_description': True}
    return render(request, 'event_details.html', context=context)

b13/hoos/templates/authenticated.html
{% extends 'base.html' %}

{% block extrahead %}{% endblock %}

{% block content %}
<center>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid">
      <a class="navbar-brand">HoosHappenings</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
      {% block nav %}{% include 'nav.html' %}{% endblock %}
        <div class="ms-auto">
        <a class="btn btn-primary" href="{% url 'logout' %}">Logout</a>
        </div>
      </div>
    </div>
  </nav>
</center>
  {% block postnav %}{% endblock %}
{% endblock %}

b13/hoos/templates/base.html
<!-- base.html -->
<!DOCTYPE html>
<html lang="en">

{% load static %}
{% load bootstrap5 %}
{% bootstrap_css %}
{% bootstrap_javascript %}

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}HoosHappenings{% endblock %}</title>
    <style>
        .event_list {
            margin-left: 5%;
            margin-right: 10%;
        }
        .event_details {
            margin-left: 10%;
            margin-right: 10%;
        }
    </style>
    {% block extrahead %}{% endblock %}
</head>
<body>
    <div id="content">
        {% block content %}{% endblock %}
    </div>
</body>
</html>

b13/hoos/templates/delete_button.html
<form method="post" action="{% url 'delete_event' event.id %}" id="deleteForm" class="d-inline">
    {% csrf_token %}
    <button type="button" class="btn btn-danger" onclick="confirmDelete()">Delete</button>
</form>

<script>
    function confirmDelete() {
        if (confirm("Are you sure you want to delete this event?")) {
        document.getElementById('deleteForm').submit();
        }
    }
</script>

b13/hoos/templates/event_details.html
{% extends 'authenticated.html' %}

{% load socialaccount %}

{% block postnav %}
<center>
<div class="event_details">
{% include 'single_event.html' %}
<p>Created by {{ event.user }} on {{ event.date_time_created }}</p>
</div>
</center>

{% endblock %}

b13/hoos/templates/home.html
{% extends 'base.html' %}

{% load socialaccount %}

{% block content %}
<center>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid">
      <a class="navbar-brand">HoosHappenings</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
      {% block nav %}{% include 'nav.html' %}{% endblock %}
          <div class="ms-auto">
          <a class="btn btn-primary" href="{% provider_login_url 'google' %}?next=/" style="margin-bottom: 10px;">Login</a>
          </div>
      </div>
    </div>
  </nav>

<h2 class="text-center">Welcome to HoosHappenings!</h2>
    <h2 class="text-center" style="font-size: 20px;">Please login to access website.</h2>
</center>
{% endblock %}

b13/hoos/templates/listings.html
{% extends 'authenticated.html' %}

{% block postnav %}
<center>
  <h1>Event Listings</h1>
</center>
<div class="event_list">
<div class="row justify-content-center">
    <div class="col-md-10">
        {% for event in events %}
            <div style="border: 1px solid #ccc; padding: 10px; margin-bottom: 20px;">
              {% include 'single_event.html' %}
              {% if user.is_superuser %}
                <a button type="submit" class="btn btn-secondary" href="{% url 'reject_event' event.id %}">Reject</a>
                {% include 'delete_button.html' %}
              {% endif %}
            </div>
              {% empty %}
              <p>No events available.</p>
        {% endfor %}
    </div>
    <div class="col-md-2">
        <form method="get">
            <label>Search by Name:</label>
            <div class="input-group">
                <input type="text" class="form-control" name="name" {% if name %} value="{{ name }}"{% endif %} style="margin-bottom: 10px">
                <div class="input-group-append">
                    <button type="submit" class="btn btn-primary" style="margin-bottom: 5px">Search</button>
                </div>
            </div>
            <div style="padding-bottom: 5px;">
                <label>Events After:</label>
                <input type="datetime-local" name="after" {% if date.0 %} value="{{ date.0 }}"{% endif %}>
                <label>Events Before:</label>
                <input type="datetime-local" name="before" {% if date.1 %} value="{{ date.1 }}"{% endif %}>
            </div>
            <div>
                <label class="form-label">Tags:</label>
                {{ form.tags }}
            </div>
            <button type="submit" class="btn btn-primary">Filter</button>
            {% if show %}
                <a href="{% url 'listings' %}"><button type="button" class="btn btn-secondary">Remove All Filters</button></a>
            {% endif %}
        </form>
    </div>
</div>
</div>
{% endblock %}

b13/hoos/templates/map.html
{% extends 'authenticated.html' %}

{% block postnav %}
<div id="map-and-search-container">
    <input type="text" id="location-input" placeholder="Search for a location..." style="width: 55%; height: 30px;">
    <div id="map"></div> <!-- Container for the map -->
    <div id="search-container">
        <form method="get" style="padding-bottom: 10px">
            <label>Search by Name:</label>
            <div>
                <input type="text" name="name" {% if name %} value="{{ name }}"{% endif %} style="margin-bottom: 10px">
            </div>
            <button type="submit" class="btn btn-primary" style="margin-bottom: 10px">Search</button>
            <div style="padding-bottom: 5px;">
                <label style="display: block">Events After:</label>
                <input type="datetime-local" name="after" {% if date.0 %} value="{{ date.0 }}"{% endif %}>
            </div>
            <div>
                <label style="display: block">Events Before:</label>
                <input type="datetime-local" name="before" {% if date.1 %} value="{{ date.1 }}"{% endif %}>
            </div>
            <div style="margin-bottom: 10px">
                <label class="form-label">Tags:</label>
                {{ form.tags }}
            </div>
            <button type="submit" class="btn btn-primary">Filter</button>
            {% if show %}
                <a href="{% url 'map' %}"><button type="button" class="btn btn-secondary">Remove All Filters</button></a>
            {% endif %}
        </form>
        <div id="event-list"></div> <!-- Container for listing events -->
    </div>
</div>

<style>
    #map-and-search-container {
        display: flex;
    }

    #map {
        height: 700px;
        width: 60%;
    }

    #search-container {
        width: 30%; /* Adjust the width as needed */
        padding: 10px;
        box-sizing: border-box; /* Include padding in width calculation */
    }

    #event-list {
        margin-top: 20px;
        max-height: 400px; /* Adjust as needed */
        overflow-y: auto; /* Scrollable list */
    }
</style>

<script>
    function initMap() {
        const mapOptions = {
            center: { lat: 38.0293, lng: -78.4767 }, // Charlottesville, VA
            zoom: 10
        };

        const map = new google.maps.Map(document.getElementById('map'), mapOptions);
        // const eventsData = {{ events }};
    
        // console.log(eventsData);
                    {% for event in events %}
        console.log("{{event.name}}")
        var marker = new google.maps.Marker({
        position: { lat: {{ event.latitude }}, lng: {{ event.longitude }} },
        map: map,
        title: "{{ event.name }}"
        });

        // Create an infowindow for the user's location
        var eventLocation = new google.maps.InfoWindow({
            content: '<a href="{% url 'event_details' event_id=event.id %}">{{ event.name }}</a>'
        });

        // Add a click event listener to the userLocationMarker to display the infowindow
        marker.addListener("click", (function (eventLocation, marker) {
            return function (){
                eventLocation.open(map, marker);
            };
        })(eventLocation, marker));

    {% endfor %}


        if (navigator.geolocation) {
            navigator.geolocation.getCurrentPosition(function (position) {
                const userLocation = {
                    lat: position.coords.latitude,
                    lng: position.coords.longitude
                };
                map.setCenter(userLocation);

                // Create a marker for the user's location
                const userLocationMarker = new google.maps.Marker({
                    position: userLocation,
                    map: map,
                    title: "Your Location"
                });

                // Create an infowindow for the user's location
                const userLocationInfowindow = new google.maps.InfoWindow({
                    content: "Your Location"
                });

                // Add a click event listener to the userLocationMarker to display the infowindow
                userLocationMarker.addListener("click", function () {
                    userLocationInfowindow.open(map, userLocationMarker);
                });
            });
        }

        const input = document.getElementById('location-input');
        const searchBox = new google.maps.places.SearchBox(input);
        map.controls[google.maps.ControlPosition.TOP_CENTER].push(input);

        searchBox.addListener('places_changed', function () {
            const places = searchBox.getPlaces();
            if (places.length === 0) {
                return;
            }


            const bounds = new google.maps.LatLngBounds();
            places.forEach(function (place) {
                if (!place.geometry) return;
                if (place.geometry.viewport) {
                    bounds.union(place.geometry.viewport);
                } else {
                    bounds.extend(place.geometry.location);
                }
            });
            map.fitBounds(bounds);
        });
    }
</script>
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBFnP0Yo4IN8h8Q1U4SjPKdJH9X1QeiKMc&libraries=places&callback=initMap"
        async defer></script>

{% endblock %}

b13/hoos/templates/my_events.html
{% extends 'authenticated.html' %}

{% block postnav %}
<center>
  <h1>My Events</h1>
</center>
<div class="event_list">
{% for event in events %}
    <div style="border: 1px solid #ccc; padding: 10px; margin-bottom: 20px;">
      {% include 'single_event.html' %}
      <p><strong>Status:</strong> {{ event.get_approval_status_display }}</p>
      {% if user.is_superuser %}
      {% if event.approval_status != 'approved' %}
        <a button type="submit" class="btn btn-primary" href="{% url 'approve_event' event.id %}">Approve</a>
      {% endif %}
      {% if event.approval_status != 'rejected' %}
        <a button type="submit" class="btn btn-secondary" href="{% url 'reject_event' event.id %}">Reject</a>
      {% endif %}
      {% endif %}
      {% include 'delete_button.html' %}
    </div>
      {% empty %}
      <p>No events available.</p>
  {% endfor %}
</div>
{% endblock %}

b13/hoos/templates/nav.html
<ul class="navbar-nav">
    <li class="nav-item">
        <a class="nav-link" href="{% url 'welcome' %}">Home</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" href="{% url 'listings' %}">Event Listings</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" href="{% url 'map' %}">Map of Nearby Events</a>
    </li>
        <li class="nav-item">
        <a class="nav-link" href="{% url 'submit_event' %}">Submit an Event</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" href="{% url 'my_events' %}">My Events</a>
    </li>
    {% if user.is_superuser %}
    <li class="nav-item">
        <a class="nav-link" href="{% url 'review_events' %}">Review Events</a>
    </li>
    {% endif %}
</ul>
  

b13/hoos/templates/review.html
{% extends 'authenticated.html' %}

{% block postnav %}
<center>
  <h1>Review Events</h1>
</center>
<div class="event_list">
{% for event in events %}
  <div style="border: 1px solid #ccc; padding: 10px; margin-bottom: 20px;"></divstyle>
    {% include 'single_event.html' %}
    <a button type="submit" class="btn btn-primary" href="{% url 'approve_event' event.id %}">Approve</a>
    <a button type="submit" class="btn btn-secondary" href="{% url 'reject_event' event.id %}">Reject</a>
  </div>
    {% empty %}
    <p>No events to approve.</p>
{% endfor %}
</div>
{% endblock %}

b13/hoos/templates/single_event.html
<h3><a href="{% url 'event_details' event_id=event.id %}">{{ event.name }}</a></h3>
{% if long_description %}
<p>{{ event.description|linebreaks }}</p>
{% else %}
<p>{{ event.description|truncatechars:50|linebreaks }}</p>
{% endif %}
<p>📍 <a href="https://www.google.com/maps/search/?api=1&query={{ event.location }}" target="_blank">{{ event.location }}</a></p>
<p>🕒 {{ event.date_time }}</p>
<p>🏷️
{% for tag in event.tags.all %}
    {{ tag.name }}
    {% if not forloop.last %}|{% endif %}
{% endfor %}    
</p>

b13/hoos/templates/submit.html
{% extends 'authenticated.html' %}

{% block postnav %}
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBFnP0Yo4IN8h8Q1U4SjPKdJH9X1QeiKMc&libraries=places&callback=initAutocomplete" async defer></script>
  <div class="container mt-3">
    <h2>Submit Event</h2>
    <form method="post">
      {% csrf_token %}
      <div class="row">
        <div class="col-md-6">
          <div class="mb-3">
            <label class="form-label">Event Name:</label>
            {{ form.name }}
          </div>
          <div class="mb-3">
            <label class="form-label">Event Description:</label>
            {{ form.description }}
          </div>
          <div class="mb-3">
            <label class="form-label">Event Location:</label>
            {{ form.location }}
            <span class="help-text">{{ form.location.help_text }}</span>
          </div>
          <div class="mb-3">
            <label class="form-label">Date and Time:</label>
            {{ form.date_time }}
          </div>
        </div>
        <div class="col-md-6">
          <div class="mb-3">
              <label class="form-label">Tags:</label>
              {{ form.tags }}
          </div>
        </div>
        {% for error in form.date_time.errors %}
        <p class="text-danger">{{ error }}</p>
        {% endfor %}
      </div>
      <button type="submit" class="btn btn-primary">Submit Event</button>
    </form>
  </div>
  <script>
    function initAutocomplete() {
        var input = document.getElementById('autocomplete');
        var autocomplete = new google.maps.places.Autocomplete(input);
    }
  </script>
  
{% endblock %}

b13/hoos/templates/submit_confirmation.html
{% extends 'authenticated.html' %}

{% block postnav %}
<center>
<h2>Thank you!</h2>
<p>
    Thank you for submitting the event "{{ submission.name }}"!
    Please wait until an admin approves your event before you can see it listed.
</p>
{% if not valid_location %}
    <p style="color: red; font-weight: bold;">
        Warning: The location you submitted is not in Google Maps, so it will not show up on the map.
    </p>
{% endif %}
<a button type="submit" class="btn btn-primary" href="{% url 'submit_event' %}">Submit another event</a>
<a button type="submit" class="btn btn-primary" href="{% url 'listings' %}">See Event Listings</a>

<p>
    <br>
    You can also monitor the status of your event here:
</p>
<a button type="submit" class="btn btn-primary" href="{% url 'my_events' %}">My Events</a>
</center>
{% endblock %}

b13/hoos/templates/welcome.html
{% extends 'authenticated.html' %}

{% load socialaccount %}

{% block postnav %}
<center>
<h2 class="text-center">Welcome to HoosHappenings!</h2>
<p>You are signed in as {{ user }} with the account {{ user.email }} as {{ user_type }}.</p>

    <div id="image-container"></div>

    <script type="text/javascript">
        function displayImage(url) {
            const imageContainer = document.getElementById('image-container');
            const img = document.createElement('img');
            img.src = url;
            img.alt = 'Display Image';
            imageContainer.appendChild(img);
        }

        // Call the function with the URL passed from Django context
        displayImage('{{ "https://images.fineartamerica.com/images-medium-large-5/university-of-virginia-academical-village-maria-rabinky.jpg" }}');
    </script>
</center>
{% endblock %}